### ISSUE TITLE
Unset white background of SVG

### ISSUE THREAD

**Issue by vwkd** [microsoft/vscode-notebook-renderers#192]
## Description

Currently, the SVG renderer forces the background to be white which doesn’t play well with dark mode. This is unlike the built-in renderer in VSCode which doesn't set it.

It’s caused by the following [rule](https://github.com/microsoft/vscode-notebook-renderers/blob/be0ac118adb82c285f97d5817cea159c1d954594/src/client/index.css#L12) targeting the wrapping div.

```css
.svgContainerStyle svg {
  background-color: white;
}
```

## Steps To Reproduce

See https://github.com/denoland/deno/issues/22427

## Expected Result

<img width="1440" alt="expected" src="https://github.com/denoland/deno/assets/33468089/b10cbbb4-0dad-42e0-8006-740c2e6e447a">

## Actual Result

<img width="1440" alt="actual" src="https://github.com/denoland/deno/assets/33468089/139a3967-628d-4f85-b368-cff940919c7a">

## Additional Information

- Jupyter v2024.1.1

**Comment by Seally** [comment]
I think the white background is intentional given this commit message: https://github.com/microsoft/vscode-notebook-renderers/commit/585e64138283cb420df3f35eb3d926cea81924cc

The main reason is that if you don't want the white background you can use the built-in renderer, otherwise there would be no need to have two renderers for the same content type. Some SVGs simply expect the output to be rendered on a white background.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, unfortunately as @Seally mentioned this was deliberate.
Currently we have no plans on changing this.
Closing as not planned
